// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUZEL2hxUkVXRTluY0taSUk2QzNaUktGa0FnVEx4bDZ4YVd5Y2xtbzUzND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoickZHTDlUdWNwOFVCdW5mUUJIZXVia2NyZUk1RzE5NW1QS2tvdEora2hsZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1QTFWMnUwcjRCUWtLSlBPVkovVzRXRW1aLzNLa3F0WExRY25LVVQzaDA0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjRUxSOHVzUFBOUUlVZklVS0I5QmxDQmNTU0VGL0ZqUVlETXoxYWFDK3lFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVPdGxpTVJuMWt2dnVoOWxNV0VOQ0NvQWNKa25HS29VNUdwRGtpNGsyblU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZNYlNidFhPcHBBeWVIU01LRmdXVjljNnVMSUZqeE1aZ2NIZ293V3JYMzQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUZkdTFkMkNCaGtZWWFoc0x2NXFVSDBxMGE2Mlk1MzB6TEVyK0UyU1lYND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVVZFNWMveU1XSjd5djZaWFJ3bDZCZ1ZqSVB0Y2o3VXNuUkhFbzdYYitqST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImxCL3hqbWlPcnFvdm9DTUkwSHNxVWJRRmhRLzZqdEpqU1BISEk5NVBscXJiOVFiRU5hMDhBNFpWc1IxZEVaeXI0ZG1lQk1pTkxtK0ZDVHRmMENQTGp3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NDIsImFkdlNlY3JldEtleSI6IkJvZUVhZUZSRFhQNDFwSW8vQVFiK1V5ZVU1V0ZPTzBRN3plUElrMnhRSlk9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6ImJJU0RYR1I3UkxHdVVWbW83UThtVmciLCJwaG9uZUlkIjoiOWYzYjJiMWMtMGQ1NS00YTg5LWFiNGEtYmY0NzNjOTI3ZTc4IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Iml3S0Y4QWhWdnpwQko4MjhaMFhoUUo1dnpDOD0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1WG85K0U4d1FXcmliNTdxeThoL0xvbUFhVXM9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiVzJKWFBWRTEiLCJtZSI6eyJpZCI6IjIzNDgxMjI0NDEyNDQ6ODBAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ052djdJUUVFTkRONnJnR0dBUWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlRVTDBPK2dFNkN0dExvOXc4Qi9ZRnFHWGVXVmh5RytISmNVN25UUXowUkk9IiwiYWNjb3VudFNpZ25hdHVyZSI6Im5mZy93Z1AvTTNJNmNzbWZrb0g5dUNmaWJjTDBacUJzWEQ4Q2VaSHhYTlNZaTVmVXpKNEdkaWVwa1E1YnNOVXJiTEFGM1RYRHN3WnorQ2JCZzk5S0JBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiIwb2h1QmR6RGNJT2hIaXI1MFpqN0NMR2w1WXB1MWl4VWFqZ1FJWnR0ZkdVK2J3Ni9JaVN3Q01vaWlvTmJqYmFTZUZtSzUySW5KME53VVAvV0NBT2RqUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDgxMjI0NDEyNDQ6ODBAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVTFDOUR2b0JPZ3JiUzZQY1BBZjJCYWhsM2xsWWNodmh5WEZPNTAwTTlFUyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyOTc5OTkwM30=",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "Dark-Love-MD",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "2348122441244",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
